# merge-context.ps1
# Merges startup context, team context, session context, and agent prompt into single file
# Usage: merge-context.ps1 <agent-prompt-name>
# Example: merge-context.ps1 team-lead.md

param(
    [Parameter(Mandatory=$true)]
    [string]$AgentPrompt
)

$ErrorActionPreference = "Stop"

# Paths
$agentsDir = "D:\dev\agents"
$contextDir = "D:\dev\agents\context"
$promptsDir = "D:\dev\agents\prompts"
$tempDir = "D:\dev\agents\temp"

$startupContextFile = Join-Path $agentsDir "STARTUP-CONTEXT.md"
$teamRosterFile = Join-Path $agentsDir "TEAM-ROSTER.md"
$archIndexFile = Join-Path $agentsDir "ARCHITECTURE-INDEX.md"
$teamContextFile = Join-Path $contextDir "team-context.md"
$sessionContextFile = Join-Path $contextDir "session-context.md"
$agentPromptFile = Join-Path $promptsDir $AgentPrompt
$outputFile = Join-Path $tempDir "merged-$AgentPrompt"

# Ensure temp directory exists
if (-not (Test-Path $tempDir)) {
    New-Item -ItemType Directory -Path $tempDir -Force | Out-Null
}

# Start building merged content
$mergedContent = @"
# MERGED AGENT PROMPT WITH CONTEXT
# Auto-generated by Context Persistence System v2.0
# Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

**🚨 CRITICAL: This merged file contains ALL context you need at startup**

---

"@

# Add startup context (always present - FIRST!)
if (Test-Path $startupContextFile) {
    $mergedContent += @"
# ⚡ STARTUP CONTEXT (Read This FIRST!)

**🚨 CRITICAL: Essential startup information for ALL agents**

"@
    $mergedContent += Get-Content $startupContextFile -Raw
    $mergedContent += @"


---

"@
} else {
    Write-Warning "Startup context file not found: $startupContextFile"
}

# Add team roster (optional but recommended)
if (Test-Path $teamRosterFile) {
    $mergedContent += @"
# 👥 TEAM ROSTER (Know Your Colleagues!)

**For detailed agent profiles and expertise, see this section**

"@
    $mergedContent += Get-Content $teamRosterFile -Raw
    $mergedContent += @"


---

"@
} else {
    Write-Host "Team roster file not found (optional): $teamRosterFile" -ForegroundColor Yellow
}

# Add architecture index (optional but recommended)
if (Test-Path $archIndexFile) {
    $mergedContent += @"
# 🏗️ ARCHITECTURE INDEX (Document Reference)

**Quick reference to all architecture documents**

"@
    $mergedContent += Get-Content $archIndexFile -Raw
    $mergedContent += @"


---

"@
} else {
    Write-Host "Architecture index file not found (optional): $archIndexFile" -ForegroundColor Yellow
}

# Add team context (persistent state)
if (Test-Path $teamContextFile) {
    $mergedContent += @"
# 📊 TEAM CONTEXT (Persistent State)

**🚨 CRITICAL: Current team state across all projects**

"@
    $mergedContent += Get-Content $teamContextFile -Raw
    $mergedContent += @"


---

"@
} else {
    Write-Warning "Team context file not found: $teamContextFile"
}

# Add session context (current work)
if (Test-Path $sessionContextFile) {
    $mergedContent += @"
# 🔄 SESSION CONTEXT (Current Work)

**🚨 CRITICAL: This is what we're working on RIGHT NOW**

"@
    $mergedContent += Get-Content $sessionContextFile -Raw
    $mergedContent += @"


---

"@
} else {
    Write-Host "Session context file not found (OK if first run): $sessionContextFile" -ForegroundColor Yellow
}

# Add agent prompt (always present)
if (Test-Path $agentPromptFile) {
    $mergedContent += @"
# 🤖 AGENT PROMPT (Your Role & Instructions)

**Your specific role, expertise, and instructions**

"@
    $mergedContent += Get-Content $agentPromptFile -Raw
} else {
    Write-Error "Agent prompt file not found: $agentPromptFile"
    exit 1
}

# Write merged content
$mergedContent | Out-File -FilePath $outputFile -Encoding UTF8 -Force

# Success summary
Write-Host ""
Write-Host "✅ Context merged successfully" -ForegroundColor Green
Write-Host "   Startup Context: $(if (Test-Path $startupContextFile) { '✓' } else { '✗' })" -ForegroundColor $(if (Test-Path $startupContextFile) { 'Green' } else { 'Red' })
Write-Host "   Team Roster: $(if (Test-Path $teamRosterFile) { '✓' } else { '○' })" -ForegroundColor $(if (Test-Path $teamRosterFile) { 'Green' } else { 'Yellow' })
Write-Host "   Arch Index: $(if (Test-Path $archIndexFile) { '✓' } else { '○' })" -ForegroundColor $(if (Test-Path $archIndexFile) { 'Green' } else { 'Yellow' })
Write-Host "   Team Context: $(if (Test-Path $teamContextFile) { '✓' } else { '✗' })" -ForegroundColor $(if (Test-Path $teamContextFile) { 'Green' } else { 'Red' })
Write-Host "   Session Context: $(if (Test-Path $sessionContextFile) { '✓' } else { '○' })" -ForegroundColor $(if (Test-Path $sessionContextFile) { 'Green' } else { 'Yellow' })
Write-Host "   Agent Prompt: $(if (Test-Path $agentPromptFile) { '✓' } else { '✗' })" -ForegroundColor $(if (Test-Path $agentPromptFile) { 'Green' } else { 'Red' })
Write-Host "   Output: $outputFile" -ForegroundColor Cyan
Write-Host ""

exit 0
