# save-context.ps1
# Saves current session context before restart
# This script helps update session-context.md with current work

param(
    [Parameter(Mandatory=$false)]
    [string]$Message = ""
)

$ErrorActionPreference = "Stop"

# Paths
$sessionContextFile = "D:\dev\agents\context\session-context.md"
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

Write-Host "Saving session context..." -ForegroundColor Cyan

# Check if session context exists
if (-not (Test-Path $sessionContextFile)) {
    Write-Warning "Session context file not found. Creating new one..."

    # Create basic template
    $content = @"
# Session Context - Huidige Sessie

**Sessie gestart:** $timestamp
**Laatste save:** $timestamp

---

## Huidige Taken (In Progress)

$(if ($Message) { "- $Message" } else { "- [No tasks specified]" })

---

## Volgende Stappen

1. [Next action]

---

## Voltooide Acties (Deze Sessie)

- [Completed action]

---

## Laatste Activiteiten

- Session context saved at $timestamp
$(if ($Message) { "- $Message" } else { "" })

---

**Auto-generated by Context Persistence System**
**Versie:** 1.0
"@

    $content | Out-File -FilePath $sessionContextFile -Encoding UTF8 -Force
    Write-Host "New session context created" -ForegroundColor Green

} else {
    # Update existing file - just update timestamp
    $content = Get-Content $sessionContextFile -Raw

    # Update "Laatste save" timestamp
    $content = $content -replace '(\*\*Laatste save:\*\*\s+)[\d\-:\s]+', "`$1$timestamp"

    # Add message to "Laatste Activiteiten" if provided
    if ($Message) {
        $content = $content -replace '(## Laatste Activiteiten)', "`$1`n- $timestamp - $Message"
    }

    $content | Out-File -FilePath $sessionContextFile -Encoding UTF8 -Force
    Write-Host "Session context updated" -ForegroundColor Green
}

Write-Host ""
Write-Host "Session context saved at: $sessionContextFile" -ForegroundColor Green
Write-Host "Timestamp: $timestamp" -ForegroundColor Gray

if ($Message) {
    Write-Host "Message: $Message" -ForegroundColor Gray
}

Write-Host ""
Write-Host "TIP: Edit $sessionContextFile manually voor details" -ForegroundColor Yellow
Write-Host "     Huidige taken, volgende stappen, etc." -ForegroundColor Yellow

exit 0
